ProjectAlita/application-tools

src/alita_tools/localgit/local_git.py
=> Update Local git agent

src/alita_tools/localgit/__init__.py, src/alita_tools/localgit/local_git.py
Update get_diff and toolkit instantiation.
=> Update get_diff and toolkit instantiation.

requirements.txt, src/alita_tools/localgit/local_git.py, src/alita_tools/qtest/__init__.py, src/alita_tools/qtest/api_wrapper.py, src/alita_tools/qtest/tool.py
=> Update local git tool

pyproject.toml, src/alita_tools/confluence/api_wrapper.py
Introduce 2 tools:
- update_page
- delete_page
Add support for labels (both actions: add on create_page or change on update_page)
=> Introduce update_page, delete_page, work with lables

pyproject.toml
=> Change tools version for new release

pyproject.toml, src/alita_tools/advanced_jira_mining/data_mining_wrapper.py
Fixing the search_data from advanced jira mining
=> Fixing the search_data from advanced jira mining

pyproject.toml, src/alita_tools/bitbucket/__init__.py, src/alita_tools/bitbucket/api_wrapper.py, src/alita_tools/bitbucket/tools.py, src/alita_tools/gitlab/tools.py
- cut tool's description
- introduce bitbucket toolkit for server
=> minor fixes, introduce bitbucket:

pyproject.toml, src/alita_tools/advanced_jira_mining/data_mining_wrapper.py
Fix the state transfer in preapare_data and search_data tools of advanced jira mining toolkit.
Bump version.
=> Fix the state transfer in advanced  jira mining

src/alita_tools/confluence/api_wrapper.py
simplified update Page - make 2 methods
introduce updateLabels
update search_pages with metadata
fix issue with pagination in search_pages
=> Update Confluence tools: search, update

pyproject.toml, src/alita_tools/advanced_jira_mining/data_mining_wrapper.py
Add gaps_analysis tool to advanced_jira_mining. Bump version.
=> Add gaps_analysis tool to advanced_jira_mining. Bump version.

src/alita_tools/confluence/api_wrapper.py
- rename `updatePage` to `updatePageById` (similar to `updatePageByTitle`)
- add `status: str = 'current'` to  `create_page` and `create_pages methods`
- cleanup extra symbols in logging
- add `temp_create_page` method (copied from attlassian lib, until PR to it will be merged)
- for `delete_page` rolled back additional verification `(self.client.get_page_by_title(space=self.space, title=page_title) or {}).get('id')` - will handle error if page is not found by `page_title`
=> Add create draft

src/alita_tools/confluence/api_wrapper.py
While refactoring the names, these places were accidentally skipped.
=> Fix update_page

pyproject.toml, src/alita_tools/qtest/api_wrapper.py
Fix the create_test_cases tool for Qtest toolkit. Bump version.
=> Fix the create_test_cases tool for Qtest toolkit. Bump version.

src/alita_tools/confluence/api_wrapper.py
Important metadata was added to the output
=> Update return in get_pages_with_label

pyproject.toml, src/alita_tools/__init__.py, src/alita_tools/ado/wiki/__init__.py, src/alita_tools/ado/wiki/ado_wrapper.py, src/alita_tools/ado/work_item/__init__.py, src/alita_tools/ado/work_item/ado_wrapper.py, src/alita_tools/bitbucket/cloud_api_wrapper.py
1. Bitbucket: update create new branch flow.
2. ADO: separate ado boards and wiki, introduce wiki toolkit
=> tools updates:

src/alita_tools/jira/api_wrapper.py
This is to make a reliable method to link the issues.
=> JIRA toolkit update (add method to link issues)

pyproject.toml, src/alita_tools/__init__.py, src/alita_tools/bitbucket/api_wrapper.py, src/alita_tools/github/__init__.py, src/alita_tools/github/api_wrapper.py, src/alita_tools/jira/__init__.py, src/alita_tools/jira/api_wrapper.py, src/alita_tools/testrail/__init__.py, src/alita_tools/testrail/api_wrapper.py
- github
- jira
- testrail
- bitbucket
=> fix issues after the migration

src/alita_tools/__init__.py, src/alita_tools/jira/api_wrapper.py, src/alita_tools/qtest/__init__.py, src/alita_tools/qtest/api_wrapper.py, src/alita_tools/report_portal/__init__.py
=> fix toolkits

pyproject.toml, src/alita_tools/github/api_wrapper.py, src/alita_tools/openapi/__init__.py
- openapi: add capability to replace
- github: model for pr / issue
=> Fix tools:

pyproject.toml, src/alita_tools/gitlab/api_wrapper.py, src/alita_tools/gitlab/tools.py, src/alita_tools/gitlab_org/api_wrapper.py, src/alita_tools/rally/api_wrapper.py
- gitlab: add list files by path tool;
- rally: update get_user tool
=> Update Gitlab and Rally toolkits:

src/alita_tools/ado/__init__.py, src/alita_tools/ado/repos/__init__.py, src/alita_tools/ado/repos/repos_wrapper.py
- `list_branches_in_repo`: Fetches a list of all branches in the repository
- `set_active_branch`: param(`branch_name: str`): Equivalent to `git checkout branch_name`
- `list_files_in_main_branch`: Fetches all files in the main branch of the repo
- `get_files_from_directory`: param(`directory_path: str`): Recursively fetches files from a directory in the repo
- `list_open_pull_requests`: Fetches all open pull requests from the Azure DevOps repository
- `get_pull_request`: param(`pull_request_id: str`): Fetches particular pull request from the Azure DevOps repository
- `list_pull_request_files`: param(`pull_request_id: str`): Fetches the files and their diffs included in a pull request
- `create_branch`: param(`proposed_branch_name: str`): Create a new branch in Azure DevOps
- `read_file`: …
=> Tools: Add AzureDevOps Repos (Git) tool wrapper

pyproject.toml, src/alita_tools/ado/__init__.py, src/alita_tools/ado/repos/__init__.py, src/alita_tools/ado/repos/repos_wrapper.py, src/alita_tools/bitbucket/__init__.py, src/alita_tools/bitbucket/cloud_api_wrapper.py, src/alita_tools/confluence/api_wrapper.py
- confluence (skip_images for search)
- fix bitbucket (branch reference, init selected tools)
- rename init properties for ADO repos
=> Tools update:

pyproject.toml, requirements.txt, src/alita_tools/__init__.py, src/alita_tools/ado/repos/__init__.py, src/alita_tools/ado/repos/repos_wrapper.py, src/alita_tools/sharepoint/__init__.py, src/alita_tools/sharepoint/api_wrapper.py
- fix ado repos
- update sharepoint
=> Tools update: ado + sharepoint

pyproject.toml, src/alita_tools/ado/work_item/ado_wrapper.py, src/alita_tools/sharepoint/api_wrapper.py
1) introduce link workitems;
2) update sharepoint method's description
=> Feature(59): add link workitems

src/alita_tools/ado/repos/repos_wrapper.py
This PR contains the following fixes:
- [#703](https://github.com/ProjectAlita/projectalita.github.io/issues/703). [BUG]ADO repo- list files is not working properly
- [#708](https://github.com/ProjectAlita/projectalita.github.io/issues/708). [BUG]Branch Creation Displays Success but No Branch is Created in Azure DevOps
=> Fixes of bugs for ADO Repos application tool

src/alita_tools/ado/repos/repos_wrapper.py
- `update_file` function fixed
- `delete_file` function fixed
The fix has been verified locally on main:
=> Fix update and delete file methods

src/alita_tools/gitlab_org/api_wrapper.py
fix in terms of https://github.com/ProjectAlita/projectalita.github.io/issues/720
=> fix gitlab tools

src/alita_tools/github/__init__.py
fix in terms of https://github.com/ProjectAlita/projectalita.github.io/issues/721
=> fix tool names

src/alita_tools/github/api_wrapper.py
Implement new features for GitHub [#731](https://github.com/ProjectAlita/projectalita.github.io/issues/731):
- search_issues
- create_issue
- update_issue
Examples of API tests:
- search_issues:
```python
from src.alita_tools.github import AlitaGitHubAPIWrapper
api = AlitaGitHubAPIWrapper(
github="https://github.com",
github_repository="<username>/<repo>",
github_base_branch="master",
active_branch="master",
github_access_token="<access_token>"
)
data = api.search_issues_and_prs("author:<author_name> state:open type:issue Issue title")
print(f"Data: {data}")
```
- create_issue
```python
from src.alita_tools.github import AlitaGitHubAPIWrapper
api = AlitaGitHubAPIWrapper(
github="https://github.com",
github_repository="<username>/<repo>",
github_base_branch="master", …
```
=> Implement new features in GH #731

src/alita_tools/ado/wiki/ado_wrapper.py
Fix "modify_wiki_page" method which can be used for creation new wiki as well.
It fixes issue #139 
Tested locally for **eye/main**:
@MikalaiB this PR includes the changes of @andrewfroze
=> Fix issue 139 ADO create wiki 

src/alita_tools/ado/repos/repos_wrapper.py, src/alita_tools/ado/wiki/ado_wrapper.py, src/alita_tools/ado/work_item/ado_wrapper.py, src/alita_tools/azure_ai/search/api_wrapper.py, src/alita_tools/cloud/aws/api_wrapper.py, src/alita_tools/cloud/azure/api_wrapper.py, src/alita_tools/cloud/gcp/api_wrapper.py, src/alita_tools/cloud/k8s/api_wrapper.py, src/alita_tools/code/sonar/api_wrapper.py, src/alita_tools/confluence/api_wrapper.py, src/alita_tools/custom_open_api/api_wrapper.py, src/alita_tools/github/api_wrapper.py, src/alita_tools/gitlab/tools.py, src/alita_tools/gitlab_org/api_wrapper.py, src/alita_tools/google_places/api_wrapper.py, src/alita_tools/jira/api_wrapper.py, src/alita_tools/keycloak/api_wrapper.py, src/alita_tools/pandas/api_wrapper.py, src/alita_tools/rally/api_wrapper.py, src/alita_tools/sharepoint/api_wrapper.py, src/alita_tools/testio/api_wrapper.py, src/alita_tools/yagmail/yagmail_wrapper.py, src/alita_tools/zephyr_scale/api_wrapper.py
fix according to https://github.com/ProjectAlita/application-tools/issues/138
=> fix tools models

src/alita_tools/report_portal/api_wrapper.py
rename in terms of https://github.com/ProjectAlita/projectalita.github.io/issues/751
=> rename of RP tool

src/alita_tools/github/api_wrapper.py, src/alita_tools/github/graphql_github.py, src/docs/guides/github_oauth_app.md
- Add board_repo param to `update_issue_on_project` and `create_issue_on_project` methods
- Fix pydantic models for CreateIssueOnProject and UpdateIssueOnProject
- In `graphql_github.py` fix all comparison to lower or upper case
=> Fix models, add param board-repo, adjust comparison by case

src/alita_tools/gitlab/api_wrapper.py, src/alita_tools/gitlab/tools.py
fix for https://github.com/ProjectAlita/projectalita.github.io/issues/797
=> add branch parameter to all gitlab tools

src/alita_tools/github/__init__.py
Add fix ([#803](https://github.com/ProjectAlita/projectalita.github.io/issues/803)) for private key auth in Github:
=> fix(add): Add default params to get_toolkit

src/alita_tools/ado/repos/repos_wrapper.py
This fix is for proper handling if auth token is valid and for proper checking of branches existence
=> Fix branches checks in ADO Repos

src/alita_tools/__init__.py, src/alita_tools/salesforce/__init__.py, src/alita_tools/salesforce/api_wrapper.py, src/alita_tools/salesforce/model.py
Implementation of following methods: 
"create_case" - "description": "Create a new Case"
"create_lead", "description": "Create a new Lead"
"search_salesforce", "description": "Search Salesforce with SOQL"
"update_case", "description": "Update a Case"
"update_lead", "description": "Update a Lead",
"execute_generic_rq", "description": "Execute a generic Salesforce API request."
How to configure:
```
{
"name": "SalesforceToolkit",
"description": "Toolkit for interacting with Salesforce API",
"settings": {
"base_url": "base url",
"client_id": "client_id",
"client_secret": "client_secret",
"api_version": "v59.0",
"selected_tools": [],
},
"type": "salesforce"
}
``` 
How to test:
Python script:
```python
import os
import json
from src.alita_tools.salesforce.api_wrapper import …
```
=> Salesforce toolkit implementation

src/alita_tools/github/api_wrapper.py, src/alita_tools/github/graphql_github.py
Feature request for https://github.com/ProjectAlita/projectalita.github.io/issues/916
Only with wrapper, w/o SDK
=> Feat(916): Handling other repos during creation/update GH issue

src/alita_tools/carrier/__init__.py, src/alita_tools/carrier/create_ticket_tool.py
- updated tool name for Carrier
- added Carrier icon
- updated formatiing
=> updated tool name for Carrier

src/alita_tools/carrier/__init__.py
=> updated label for Carrier

src/alita_tools/qtest/api_wrapper.py
1. Add proper stacktraces and update messages on errors. 
2. Make possible to create test cases in Qtest shared projects.
=> Add proper stacktraces and update messages on errors. Make possible to create test cases in Qtest shared projects.

requirements.txt, src/alita_tools/sharepoint/api_wrapper.py
in terms of https://github.com/ProjectAlita/projectalita.github.io/issues/985
Added parsing of text content from .pdf and .pptx files to sharepoint toolkit
=> add possibility to read pdf and pptx files from sharepoint

src/alita_tools/salesforce/api_wrapper.py
=> Salesforce fix 

src/alita_tools/figma/api_wrapper.py
Bug: [#1134](https://github.com/ProjectAlita/projectalita.github.io/issues/1134)
[BUG] Figma toolkit is not providing any data
=> fix: Figma to handle secrets properly, change error log

src/alita_tools/testrail/api_wrapper.py
- Revert from `raise` to `return` for ToolExceptions
- Revert logic of `get_cases_by_filter` method to return all data from cases
- Implemented new logic with `keys` parameter for `get_cases` (if keys is empty, then title and id are configured) and `get_cases_by_filter` (if keys is empty, then full response will be returned)
Local testing is successful
=> TestRail: use return instead raise, update get_cases and get_cases_by_filter logic

src/alita_tools/jira/api_wrapper.py
For this bug: [#1295](https://github.com/ProjectAlita/projectalita.github.io/issues/1295)
There were pattern used to find images from description (e.g., `!image1.png|width=750!`). But for attachment we had raw JSON containing links to content, so the logic did not handle it properly trying to apply regex
Tested successfully on DEV locally
=> fix: change logic for image description from attachment

requirements.txt, src/alita_tools/confluence/api_wrapper.py
See details here: [alita-sdk#116](https://github.com/ProjectAlita/alita-sdk/pull/116)
=> feat: add get page attachments for confluence
